name: deploy demo
'on':
  push:
    branches:
      - production
      - staging
    pull_request:
      - feature-**
  pull_request:
    types:
      - opened
      - reopened
      - closed
  workflow_dispatch:
env:
  REGION: us-central1
  BASE_REGISTRY: us-central1-docker.pkg.dev
  REGISTRY: branch-actions/reliable #change with artifact registry in your project
  workload_identity_provider: projects/634474131374/locations/global/workloadIdentityPools/branch-actions/providers/action #change with the provider that you have copied earlier
  service_account: workload-identity-user@branch-actions.iam.gserviceaccount.com #service account created
jobs:
  Build:
    name: Build
    if: github.event.action != 'closed'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    outputs:
      img: ${{ steps.meta.outputs.tags }}
    steps:
      - uses: 'actions/checkout@v3'
      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          token_format: access_token
          workload_identity_provider: ${{ env.workload_identity_provider }}
          service_account: ${{ env.service_account }}
      - name: Login to GCR
        uses: docker/login-action@v2
        with:
          registry: ${{ env.BASE_REGISTRY }}
          username: oauth2accesstoken
          password: '${{ steps.auth.outputs.access_token }}'
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.BASE_REGISTRY }}/${{ env.GCP_PROJECT}}/${{ env.REGISTRY }}/${{github.ref_name }}
          tags: |
            type=sha
      - id: docker-push-tagged
        name: Tag Docker image and push to Google Artifact Registry
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
  Deploy:
    name: deploy
    needs: Build
    if: github.event.action != 'closed'
    uses: ./.github/workflows/cloud_run_deploy.yml
    permissions:
      contents: 'read'
      id-token: 'write'
    with:
      workload_identity_provider: projects/634474131374/locations/global/workloadIdentityPools/branch-actions/providers/action  #change with the provider that you have copied earlier
      service_account: workload-identity-user@branch-actions.iam.gserviceaccount.com #service account created
      img: ${{needs.build.outputs.img}}
      cloud_run_name: ${GITHUB_REF##*/}${{github.event.pull_request.number }}
      region: us-central1
    #secrets:
    #  token: ${{ secrets.GITHUB_TOKEN }}
  Cleanup:
    name: cleanup
    if: github.event.action == 'closed'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          token_format: access_token
          workload_identity_provider: ${{ env.workload_identity_provider }}
          service_account: ${{ env.service_account }}
      - name: cleanup
        run: |-
          gcloud run services delete merge${{github.event.pull_request.number }} \
            --region $REGION \
            --quiet
